Use tools from nix devShell in CI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -12,10 +12,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - name: Use Node.js 20
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
+
+      - uses: DeterminateSystems/determinate-nix-action@v3
 
       # Re-use node_modules between runs until package-lock.json changes.
       - name: Cache node_modules
@@ -26,31 +24,41 @@ jobs:
           key: node_modules-${{ hashFiles('package-lock.json') }}
 
       # Re-use ~/.elm between runs until elm.json or review/elm.json changes.
-      # The Elm compiler saves downloaded Elm packages to ~/.elm saves
-      # downloaded tool executables there.
+      # The Elm compiler saves downloaded Elm packages to ~/.elm
       - name: Cache ~/.elm
         uses: actions/cache@v4
         with:
           path: ~/.elm
-          key: elm-${{ hashFiles('elm.json', 'review/elm.json') }}
+          key: |
+            elm-${{ hashFiles(
+              'elm.json',
+              'review/elm.json',
+              'elm-open-api-codegen/elm.json',
+              'elm-open-api-codegen/review/elm.json'
+            )}}
+
 
       # Install npm packages, unless we restored them from cache.
       # Since `npm ci` removes the node_modules folder before running it’s
       # important to skip this step if cache was restored.
       - name: npm ci
         if: steps.cache-node_modules.outputs.cache-hit != 'true'
-        run: npm ci
+        run: nix develop --command npm ci
 
       # TEMPORARY UNTIL elm-open-api-codegen IS PUBLISHED
       - name: TEMP HACK
-        run: npm run link-local-package
+        run: nix develop --command npm run link-local-package
 
       - name: Format
-        run: npm run format
+        run: nix develop --command npm run format
       - name: Review
-        run: npm run review
+        run: nix develop --command npm run review
       - name: Test
-        run: npm run test
+        run: nix develop --command npm run test
+
+      # TEMPORARY UNTIL elm-open-api-codegen IS PUBLISHED
+      - name: TEMP HACK
+        run: nix develop --command npm run unlink-local-package
 
   diff-generation:
     permissions:
@@ -58,11 +66,6 @@ jobs:
       pull-requests: write
     runs-on: ubuntu-latest
     steps:
-      - name: Use Node.js 20
-        uses: actions/setup-node@v4
-        with:
-          node-version: 20
-
       - name: Checkout branch
         uses: actions/checkout@v4
         with:
@@ -73,6 +76,8 @@ jobs:
         with:
           ref: main
           path: main
+
+      - uses: DeterminateSystems/determinate-nix-action@v3
 
       # Re-use node_modules between runs until package-lock.json changes.
       - name: Cache node_modules (branch)
@@ -91,13 +96,22 @@ jobs:
           key: node_modules-${{ hashFiles('main/package-lock.json') }}
 
       # Re-use ~/.elm between runs until elm.json or review/elm.json changes.
-      # The Elm compiler saves downloaded Elm packages to ~/.elm saves
-      # downloaded tool executables there.
+      # The Elm compiler saves downloaded Elm packages to ~/.elm.
       - name: Cache ~/.elm (both)
         uses: actions/cache@v4
         with:
           path: ~/.elm
-          key: elm-${{ hashFiles('main/elm.json', 'main/review/elm.json', 'branch/elm.json', 'branch/review/elm.json') }}
+          key: |
+            elm-${{ hashFiles(
+              'main/elm.json',
+              'main/review/elm.json',
+              'main/elm-open-api-codegen/elm.json',
+              'main/elm-open-api-codegen/review/elm.json',
+              'branch/elm.json',
+              'branch/review/elm.json',
+              'branch/elm-open-api-codegen/elm.json',
+              'branch/elm-open-api-codegen/review/elm.json'
+            )}}
 
       # Install npm packages, unless we restored them from cache.
       # Since `npm ci` removes the node_modules folder before running it’s
@@ -105,7 +119,7 @@ jobs:
       - name: npm ci (branch)
         if: steps.cache-node_modules-branch.outputs.cache-hit != 'true'
         working-directory: branch
-        run: npm ci
+        run: nix develop --command npm ci
 
       # Install npm packages, unless we restored them from cache.
       # Since `npm ci` removes the node_modules folder before running it’s
@@ -113,19 +127,23 @@ jobs:
       - name: npm ci (main)
         if: steps.cache-node_modules-main.outputs.cache-hit != 'true'
         working-directory: main
-        run: npm ci
+        run: nix develop --command npm ci
   
       # TEMPORARY UNTIL elm-open-api-codegen IS PUBLISHED
       - name: TEMP HACK
-        run: npm run link-local-package
+        run: nix develop --command npm run link-local-package
 
       - name: Generate (branch)
         working-directory: branch
-        run: npm run test:gen
+        run: nix develop --command npm run test:gen
   
       - name: Generate (main)
         working-directory: main
-        run: npm run test:gen || true # We don't want to block on main failing to generate
+        run: nix develop --command npm run test:gen || true # We don't want to block on main failing to generate
+
+      # TEMPORARY UNTIL elm-open-api-codegen IS PUBLISHED
+      - name: TEMP HACK
+        run: nix develop --command npm run unlink-local-package
 
       - name: Diff the outputs
         run: |
